### ISSUE TITLE
Additional instructions needed for manual build of libbgcode

### ISSUE THREAD

**Issue by b-morgan** [jneilliii/OctoPrint-BGCode#1]
In [building.md](https://github.com/prusa3d/libbgcode/blob/main/doc/building.md) it says:

> where \<install-dir\> is an arbitrary install folder.

and I'm guessing you are expecting the library to be somewhere so your instructions show say where that is.

**Comment by jneilliii** [comment]
Yeah, until I'm able to test this on a Linux machine I'm not going to say, but in Windows I ran a few different options until it actually compiled without errors. Maybe instructions should be better defined on the dependency repo too.

**Comment by jneilliii** [comment]
I think I got the auto-install to work (at least with octopi images) and have updated the readme with additional details.

**Comment by b-morgan** [comment]
On my RPi 4B (OctoPi 1.0.0 new camera stack) I was able to upload and "print" a .bgcode file on a virtual printer so I believe you can close this issue.
