### ISSUE TITLE
PrusaSlicer 2.7.1 changed  the location of 'export as gcode' option.

### ISSUE THREAD

**Issue by frioSC** [jneilliii/OctoPrint-BGCode#10]
Just a heads up that in the latest PrusaSlicer (2.7.1) released yesterday, they have moved the 'Export as binary G-code' option to the Printer Settings tab as 'Supports binary G-Code'.  Might want to consider updating the OctoPrint plugins page at: https://plugins.octoprint.org/plugins/bgcode/?utm_source=octoprint&utm_medium=announcements&utm_content=1.9.3
![2023-12-14 12_01_05-PrusaSlicer - Settings](https://github.com/jneilliii/OctoPrint-BGCode/assets/36449997/776e113c-0b0f-46a3-aae3-427000fc60ae)

**Comment by jneilliii** [comment]
thanks for the heads up. I've updated the plugin listing on the repository with this new information.
