### ISSUE TITLE
File extension stays .bgcode

### ISSUE THREAD

**Issue by andreasbrett** [jneilliii/OctoPrint-BGCode#4]
Thanks for quickly making this plugin possible. It works without issues so far on my OctoPi install. Not sure of this is intended or technically required but the file extension stays .bgcode after successful conversion.

**Comment by jneilliii** [comment]
That's just how it worked out. If you download the file back from OctoPrint you'll notice you can open it in a text editor. Didn't feel worth the extra effort to rename the extension.
