### ISSUE TITLE
Layer indicator not found

### ISSUE THREAD

**Issue by bradleyallanpatterson** [jneilliii/OctoPrint-BGCode#6]
Just moved to latest prusa mini FW version 5.1.0.  I installed the latest BGODE plugin to OP and then sent an BGODE to OP.

Layer indicator not found in file: '02a-z-axis-motor-mount-side-p2_0.4n_0.2mm_PLA_MINI_48m.aw.bgcode'
Check 'layer pattern', 'Look ahead limit' in DisplayLayerProgress-Settings and reUpload the file!

Looking online, people say to add the below line to the custom Gode section but I still get the above error.

;LAYER:[layer_num]

**Comment by jneilliii** [comment]
I'm sorry but I can't control/fix anything related to processing of the files once it's been converted from binary format to ascii. If you are getting unexpected results, I suggest you open issues with PrusaSlicer and any perspective plugin that is unable to process the file once it has been converted. This plugin is doing it's job with the tools provided by Prusa at this time.

**Comment by bradleyallanpatterson** [comment]
How do I know if its PS or the plugin?
I cannot open the PS file since its in binary.

**Comment by jneilliii** [comment]
So I just tested this and it does appear to be adding the wanted information. After uploading the file you can download it back from OctoPrint and open in a text editor. I added the bit you mentioned and this was what was added to my file.

```
;AFTER_LAYER_CHANGE
;0.2
;LAYER:0
...
;AFTER_LAYER_CHANGE
;0.4
;LAYER:1
```

so not sure what DisplayLayerProgress is complaining about, might need to open an issue on that plugin's repository instead.

**Comment by bradleyallanpatterson** [comment]
I disabled the Display Layer indicator plugin and OP still not working.   The exported bgcode prints fine from usb,..

**Comment by jneilliii** [comment]
I'll need full logs then and example bgcode file to test.

**Comment by jneilliii** [comment]
And prior to grabbing the logs and looking, enable the debug option for `octoprint.plugins.bgcode` in the logging settings of OctoPrint at the bottom.

![image](https://github.com/jneilliii/OctoPrint-BGCode/assets/5249455/d01bf0f5-3ef7-47ab-88cb-f0f5fe826e09)
